export const freeTimeConst = [
      { id : 1, morning: false, afternoon: false, evening: false, dayName: "CN" },
      { id : 2, morning: false, afternoon: false, evening: false, dayName: "Thứ 2" },
      { id : 3, morning: false, afternoon: false, evening: false, dayName: "Thứ 3" },
      { id : 4, morning: false, afternoon: false, evening: false, dayName: "Thứ 4" },
      { id : 5, morning: false, afternoon: false, evening: false, dayName: "Thứ 5" },
      { id : 6, morning: false, afternoon: false, evening: false, dayName: "Thứ 6" },
      { id : 7, morning: false, afternoon: false, evening: false, dayName: "Thứ 7" }
];

export const  subjectConst = [
      {id: 1, subjectName: 'Toán', status: false},
      {id: 2, subjectName: 'Vật lý', status: false},
      {id: 3, subjectName: 'Hóa học', status: false},
      {id: 4, subjectName: 'Ngữ văn', status: false},
      {id: 5, subjectName: 'Sinh học', status: false},
      {id: 6, subjectName: 'Lịch sử', status: false},
      {id: 7, subjectName: 'Địa lý', status: false},
      {id: 8, subjectName: 'Báo bài', status: false},
      {id: 9, subjectName: 'Tiếng Anh', status: false},
      {id: 10, subjectName: 'Tiếng Việt', status: false},
      {id: 11, subjectName: 'Tiếng Trung', status: false},
      {id: 12, subjectName: 'Tiếng Hàn', status: false},
      {id: 13, subjectName: 'Tiếng Nhật', status: false},
      {id: 14, subjectName: 'Đàn nhạc', status: false},
      {id: 15, subjectName: 'Tin học', status: false},
      {id: 16, subjectName: 'Vẽ', status: false},
];

export const districtConst = [
      {id: 1, districtName: 'Quận 1', status: false},
      {id: 2, districtName: 'Quận 2', status: false},
      {id: 3, districtName: 'Quận 3', status: false},
      {id: 4, districtName: 'Quận 4', status: false},
      {id: 5, districtName: 'Quận 5', status: false},
      {id: 6, districtName: 'Quận 6', status: false},
      {id: 7, districtName: 'Quận 7', status: false},
      {id: 8, districtName: 'Quận 8', status: false},
      {id: 9, districtName: 'Quận 9', status: false},
      {id: 10, districtName: 'Quận 10', status: false},
      {id: 11, districtName: 'Quận 11', status: false},
      {id: 12, districtName: 'Quận 12', status: false},
      {id: 13, districtName: 'Quận Thủ Đức', status: false},
      {id: 14, districtName: 'Quận Bình Thạnh', status: false},
      {id: 15, districtName: 'Quận Bình Tân', status: false},
      {id: 16, districtName: 'Quận Bình Chánh', status: false},
      {id: 17, districtName: 'Quận Tân Bình', status: false},
      {id: 18, districtName: 'Quận Tân Phú', status: false},
      {id: 19, districtName: 'Quận Gò Vấp', status: false},
      {id: 20, districtName: 'Quận Phú Nhuận', status: false},
      {id: 21, districtName: 'Huyện Nhà Bè', status: false},
      {id: 22, districtName: 'Huyện Hóc Môn', status: false},
      {id: 23, districtName: 'Huyện Củ Chi', status: false},
      {id: 24, districtName: 'Huyện Cần Giờ', status: false},
];

export const classTeachConst = [
      {id: 1, classTeachName: 'Lớp 1', status: false},
      {id: 2, classTeachName: 'Lớp 2', status: false},
      {id: 3, classTeachName: 'Lớp 3', status: false},
      {id: 4, classTeachName: 'Lớp 4', status: false},
      {id: 5, classTeachName: 'Lớp 5', status: false},
      {id: 6, classTeachName: 'Lớp 6', status: false},
      {id: 7, classTeachName: 'Lớp 7', status: false},
      {id: 8, classTeachName: 'Lớp 8', status: false},
      {id: 9, classTeachName: 'Lớp 9', status: false},
      {id: 10, classTeachName: 'Lớp 10', status: false},
      {id: 11, classTeachName: 'Lớp 11', status: false},
      {id: 12, classTeachName: 'Lớp 12', status: false},
      {id: 13, classTeachName: 'Ôn đại học', status: false},
      {id: 14, classTeachName: 'Lớp năng khiếu', status: false},
      {id: 15, classTeachName: 'Lớp ngoại ngữ', status: false},
      {id: 16, classTeachName: 'Lớp khác', status: false},
]

